### ISSUE TITLE
Problem in xtset2, check 3)

### ISSUE THREAD

**Issue by cg89x** [JanDitzen/xtdcce2#12]
Hi Jan, 

I noticed a small bug in xtset2.ado, line 90: `svmat` creates the variable but appends an extra 1 at the end, i.e. `Tmat1` instead of `Tmat`. This makes xtset2 fail when using `set varabbrev off`. This behavior also occurs in line 107 with `sum`. 

Best,

Chris

**Comment by JanDitzen** [comment]
Hi Chris,
thanks for spotting this error. It is fixed.
Cheers,
Jan
