### ISSUE TITLE
mm_which2

### ISSUE THREAD

**Issue by cg89x** [JanDitzen/xtdcce2#13]
https://github.com/JanDitzen/xtdcce2/blob/4dbda620833a5f08053291f3a62e7208f8fbffaa/xtdcce2.ado#L2042

Shouldn't this be `xtdcce2_mm_which2` ? `mm_which2` is undefined in my version of moremata.

**Comment by JanDitzen** [comment]
Thanks for spotting this. This was a bug in version 2.0 and was already fixed in version 2.1 (see beta versions). I fixed it here as well.
