### ISSUE TITLE
error with xtcse2

### ISSUE THREAD

**Issue by r-c-vincent** [JanDitzen/xtdcce2#17]
I keep on getting an error message when I try to run the codes in the help file in Stata. Can you kindly check if there are any bugs (with stata 17)? 

![image](https://user-images.githubusercontent.com/7773173/159342671-e43d3e40-cd11-484a-a9d0-e3fc9ebe25cd.png)

**Comment by JanDitzen** [comment]
Apologies, I never saw your question. can you please set mata strict off, i.e. type:
mata mata set matastrict off

This should solve the problem.
